# Generated by Django 5.1.7 on 2026-06-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_contact',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний контакт'),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_contact',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Следующий контакт'),
        ),
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки'),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('contacted', 'Связались'), ('thinking', 'Думают'), ('follow_up', 'Жду ответа'), ('trial', 'Записан на пробный'), ('client', 'Стал клиентом'), ('rejected', 'Отказ')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
