# Generated by Django 5.1.7 on 2026-06-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_last_contact_lead_next_contact_lead_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='URL источник'),
        ),
    ]
