# Generated by Django 5.1.7 on 2026-06-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_financeevent_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'Настройки пользователя', 'verbose_name_plural': 'Настройки пользователей'},
        ),
    ]
