# Generated by Django 5.1.7 on 2026-06-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_usersettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='accent_color',
            field=models.CharField(default='green', max_length=20, verbose_name='Акцентный цвет'),
        ),
    ]
