# Generated by Django 5.1.7 on 2026-07-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_usersettings_accent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lifecycle_status',
            field=models.CharField(choices=[('lead', 'Лид'), ('active', 'Активный'), ('inactive', 'Ушедший'), ('rejected', 'Отказ')], default='lead', max_length=20, verbose_name='Статус клиента'),
        ),
        migrations.AddField(
            model_name='client',
            name='source',
            field=models.CharField(blank=True, max_length=50, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='client',
            name='source_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='URL источник'),
        ),
    ]
