# Generated by Django 5.1.7 on 2026-07-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_client_lifecycle_status_client_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='source_url',
        ),
        migrations.AlterField(
            model_name='client',
            name='source',
            field=models.CharField(blank=True, choices=[('landing', 'Лендинг'), ('avito', 'Авито'), ('telegram', 'Telegram канал'), ('referral', 'Рекомендация'), ('other', 'Другое')], default='landing', max_length=50, verbose_name='Источник'),
        ),
    ]
