# Generated by Django 5.1.7 on 2026-09-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_financesnapshot_last_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolexpense',
            name='category',
            field=models.CharField(choices=[('advertising', 'Реклама'), ('software', 'Софт/Подписки'), ('taxes', 'Налоги'), ('salary', 'Зарплата'), ('other', 'Другое')], max_length=20, verbose_name='Категория расхода'),
        ),
    ]
