# Generated by Django 5.1.7 on 2026-09-15 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0038_client_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='Старый статус')),
                ('new_status', models.CharField(max_length=20, verbose_name='Новый статус')),
                ('reason', models.CharField(blank=True, max_length=100, verbose_name='Причина')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'История статуса клиента',
                'verbose_name_plural': 'История статусов клиентов',
                'ordering': ['-changed_at'],
            },
        ),
    ]
