# Generated by Django 5.1.7 on 2025-11-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')],
                                   default='medium', max_length=20, verbose_name='Приоритет'),
        ),
    ]
