# Generated by Django 5.1.7 on 2025-11-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0002_task_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(
                choices=[('backlog', 'Бэклог'), ('todo', 'К выполнению'), ('in_progress', 'В работе'),
                         ('review', 'На проверке'), ('done', 'Завершено')], default='backlog', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
