# Generated by Django 5.1.7 on 2025-11-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0003_alter_task_options_remove_task_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
