# Generated by Django 5.1.7 on 2025-11-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0004_task_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/images/', verbose_name='Изображение'),
        ),
    ]
