# Generated by Django 5.1.7 on 2025-11-20 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0006_project_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks',
                                    to='tasks.project'),
            preserve_default=False,
        ),
    ]
