# Generated by Django 5.1.7 on 2026-03-11 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название колонки')),
                ('color', models.CharField(default='#336699', max_length=7, verbose_name='Цвет колонки')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='tasks.project')),
            ],
            options={
                'verbose_name': 'Колонка проекта',
                'verbose_name_plural': 'Колонки проектов',
                'ordering': ['order'],
            },
        ),
    ]
