# Generated by Django 5.1.7 on 2026-03-11 11:19

from django.db import migrations


def create_default_columns(apps, schema_editor):
    Project = apps.get_model('tasks', 'Project')
    ProjectColumn = apps.get_model('tasks', 'ProjectColumn')

    # Дефолтные колонки для каждого проекта
    default_columns = [
        {'name': 'Бэклог', 'color': '#6c757d', 'order': 0},
        {'name': 'К выполнению', 'color': '#007bff', 'order': 1},
        {'name': 'В работе', 'color': '#ffc107', 'order': 2},
        {'name': 'На проверке', 'color': '#17a2b8', 'order': 3},
        {'name': 'Завершено', 'color': '#28a745', 'order': 4},
    ]

    # Для каждого проекта создаём колонки
    for project in Project.objects.all():
        for column_data in default_columns:
            ProjectColumn.objects.create(
                project=project,
                name=column_data['name'],
                color=column_data['color'],
                order=column_data['order']
            )


def remove_default_columns(apps, schema_editor):
    ProjectColumn = apps.get_model('tasks', 'ProjectColumn')
    # При откате удаляем все колонки
    ProjectColumn.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0008_projectcolumn'),
    ]

    operations = [
        migrations.RunPython(create_default_columns, remove_default_columns),
    ]