# Generated by Django 5.1.7 on 2026-06-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_populate_project_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('editor', 'Редактор')], default='editor', max_length=20),
        ),
    ]
